#!/bin/bash
set -e

if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then

git config user.name "Travis CI"
git config user.email "clara.linos@vizzuality.com"

git checkout -b gh-pages

git rebase develop

wepback -p

git add -f build/index.html
git add -f build/main.css
git add -f build/main.js

git commit -m 'Automatic Travis Build'

git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages > /dev/null 2>&1

fi
